<?php
// Global
$lang['site_error_backText']        = '';
$lang['site_403_errorText']         = '';
$lang['site_404_errorText']         = '';
$lang['site_500_errorText']         = '';
// Navigation
$lang['navigation_toggle']          = '';
$lang['navigation_home']            = '';
// NavigationSub
$lang['navigation_boards']          = '';
$lang['navigation_boards_all']      = '';
$lang['navigation_boards_noFraud']  = '';
$lang['navigation_boards_torI2P']   = '';
// Navigation
$lang['navigation_blogs']           = '';
$lang['navigation_shops']           = '';
$lang['navigation_warez']           = '';
$lang['navigation_useful']          = '';
$lang['navigation_vpn']             = '';
$lang['navigation_hosting']         = '';
$lang['navigation_addLink']         = '';
$lang['navigation_last5Added']      = '';
// NavigationSub
$lang['navigation_information']                       = '';
$lang['navigation_information_contact']               = '';
$lang['navigation_information_donate']                = '';
$lang['navigation_information_pricing']               = '';
$lang['navigation_information_linkUs']                = '';
$lang['navigation_information_misc']                  = '';
$lang['navigation_information_misc_changelog']        = '';
$lang['navigation_information_misc_api']              = '';
$lang['navigation_information_misc_faq']              = '';
$lang['navigation_information_misc_rssAdded']         = '';
$lang['navigation_information_misc_rssUpdated']       = '';
$lang['navigation_information_misc_siteUptime']       = '';
// Breadcrumbs
$lang['navigation_breadcrumb_home']       = '';
$lang['navigation_breadcrumb_noFraud']    = '';
$lang['navigation_breadcrumb_torI2P']     = '';
$lang['navigation_breadcrumb_search']     = '';
$lang['navigation_breadcrumb_blogs']      = '';
$lang['navigation_breadcrumb_shops']      = '';
$lang['navigation_breadcrumb_warez']      = '';
$lang['navigation_breadcrumb_useful']     = '';
$lang['navigation_breadcrumb_vpn']        = '';
$lang['navigation_breadcrumb_hosting']    = '';
$lang['navigation_breadcrumb_addLink']    = '';
$lang['navigation_breadcrumb_reportLink'] = '';
$lang['navigation_breadcrumb_contact']    = '';
$lang['navigation_breadcrumb_donate']     = '';
$lang['navigation_breadcrumb_pricing']    = '';
$lang['navigation_breadcrumb_linkUs']     = '';
$lang['navigation_breadcrumb_changelog']  = '';
$lang['navigation_breadcrumb_faq']        = '';
// Subnavigation
$lang['subnavigation_lastDbUpdate']       = '';
// Sidebar
$lang['sidebar_searchPlaceholder']    = '';
$lang['sidebar_linkQueue']            = '';
$lang['sidebar_linkQueue_added']      = '';
$lang['sidebar_linkQueue_reported']   = '';
$lang['sidebar_statistics']           = '';
$lang['sidebar_statistics_online']    = '';
$lang['sidebar_statistics_offline']   = '';
$lang['sidebar_statistics_languages'] = '';
$lang['sidebar_statistics_total']     = '';
$lang['sidebar_advertisement']        = '';
$lang['sidebar_version']              = '';
$lang['sidebar_version_changelog']    = '';
// Link us site
$lang['linkus_htmlCodeText']          = '';
$lang['linkus_bbcodeText']            = '';
// Donate site
$lang['donate_headText']              = '';
// Changelog site
$lang['changelog_head']         = '';
$lang['changelog_committed']    = '';
// Pricing site
$lang['pricing_smallHead']      = '';
$lang['pricing_smallInclude']   = '';
$lang['pricing_mediumHead']     = '';
$lang['pricing_highlight']      = '';
$lang['pricing_mediumInclude']  = '';
$lang['pricing_largeHead']      = '';
$lang['pricing_largeInclude']   = '';
$lang['pricing_perMonth']       = '';
$lang['pricing_contactUs']      = '';
// Search Site
$lang['search_nameText']                = '';
$lang['search_typeHead']                = '';
$lang['search_resetText']               = '';
$lang['search_category']                = '';
$lang['search_typeBoard']               = '';
$lang['search_typeBlog']                = '';
$lang['search_typeWarez']               = '';
$lang['search_typeVPN']                 = '';
$lang['search_typeUseful']              = '';
$lang['search_typeShop']                = '';
$lang['search_typeHosting']             = '';
// Contact us Site
$lang['contact_donateText']             = '';
$lang['contact_contactInformationText'] = ':';
$lang['contact_twitterFollow']          = '';
$lang['contact_warningHeader']          = '';
$lang['contact_warningText']            = '';
// Report Link Site
$lang['report_headText']              = '';
$lang['report_sitename']              = '';
$lang['report_url']                   = '';
$lang['report_reason']                = '';
$lang['report_reportBtn']             = '';
$lang['report_success_title']         = '';
$lang['report_success_text']          = '';
$lang['report_fail_title']            = '';
$lang['report_fail_text']             = '';
$lang['report_fail_DoubleEntry_text'] = '';

// Add Link Site
$lang['add_url']                      = '';
$lang['add_tor']                      = '';
$lang['add_i2p']                      = '';
$lang['add_facebook']                 = '';
$lang['add_twitter']                  = '';
$lang['add_category']                 = '';
$lang['add_languages']                = '';
$lang['add_pleaseSelect']             = '';
$lang['add_information']              = '';
$lang['add_information_placeholder']  = '';
$lang['add_addLink']                  = '';
$lang['add_success_title']            = '';
$lang['add_success_text']             = '';
$lang['add_fail_title']               = '';
$lang['add_fail_text']                = '';
$lang['add_facebook_placeholder']     = '';
// Hosting Site
$lang['hosting_head']                 = '';
$lang['hosting_service']              = '';
$lang['hosting_creditcard']           = '';
$lang['hosting_locations']            = '';
$lang['hosting_infoTextHead']         = '!';
$lang['hosting_infoText']             = '';
$lang['hosting_infoStartVideo']       = '';
// Footer
$lang['footer_generatedInStart']      = '';
$lang['footer_generatedInEnd']        = '';
// Language Category
$lang['promoted']        = '';
$lang['partner']         = '';
$lang['al']              = '';
$lang['ar']              = '';
$lang['az']              = '';
$lang['bs']              = '';
$lang['zh']              = '';
$lang['hr']              = '';
$lang['cz']              = '';
$lang['da']              = '';
$lang['nl']              = '';
$lang['en']              = '';
$lang['fr']              = '';
$lang['ge']              = '';
$lang['de']              = '';
$lang['gr']              = '';
$lang['id']              = '';
$lang['it']              = '';
$lang['jp']              = '';
$lang['my']              = '';
$lang['fas']             = '';
$lang['pl']              = '';
$lang['pt']              = '';
$lang['ro']              = '';
$lang['ru']              = '';
$lang['rs']              = '';
$lang['es']              = '';
$lang['th']              = '';
$lang['tr']              = '';
$lang['ua']              = '';
$lang['uz']              = '';
$lang['vn']              = '';
// Shop Category
$lang['shops_ccv']              = '';
$lang['shops_accounts']         = '';
$lang['shops_icq']              = '';
$lang['shops_drugs']            = '';
$lang['shops_rdp']              = '';
$lang['shops_flood']            = '';
$lang['shops_exploit']          = '';
$lang['shops_cccheck']          = '';
$lang['shops_iptv']             = '';
$lang['shops_other']            = '';
// Useful Category
$lang['useful_vuln']            = '';
$lang['useful_unsorted']        = '';
$lang['useful_ffaddons']        = '';
$lang['useful_cryptography']    = '';
$lang['useful_scanner']         = '';
$lang['useful_antimalware']     = '';
$lang['useful_linklist']        = '';
$lang['useful_multiuploader']   = '';
$lang['useful_exchanger']       = '';
$lang['useful_trashmail']       = '';
$lang['useful_challenges']      = '';
$lang['useful_securemail']      = '';
$lang['useful_cardsharing']     = '';
$lang['useful_toplist']         = '';
$lang['useful_nfo']             = '';
$lang['useful_ddosprotect']     = '';
$lang['useful_cryptocurrency']  = '';
$lang['useful_documentation']   = '';
$lang['useful_linkcrypter']     = '';
$lang['useful_startpage']       = '';
$lang['useful_telegramgrp']     = '';
$lang['useful_uptimechecker']   = '';
$lang['useful_pastebin']        = '';
$lang['useful_security']        = '';
$lang['useful_hackgame']        = '';
$lang['useful_serials']         = '';
$lang['useful_kodi']        	= '';
$lang['useful_jabber']        	= '';
// VPN Category
$lang['vpn_paidvpn']            = '';
$lang['vpn_vpninfo']            = '';
$lang['vpn_freevpn']            = '';
$lang['vpn_socks']              = '';
$lang['vpn_webproxy']           = '';
$lang['vpn_checker']            = '';
// Warez Category
$lang['warez_boards']           = '';
$lang['warez_anime']            = '';
$lang['warez_tvstream']         = '';
$lang['warez_ftp']              = '';
$lang['warez_documentation']    = '';
$lang['warez_ebook']            = '';
$lang['warez_xdcc']             = '';
$lang['warez_music']            = '';
$lang['warez_games']            = '';
$lang['warez_movies']           = '';
$lang['warez_mixed']            = '';
$lang['warez_android']          = '';
$lang['warez_apple']            = '';
$lang['warez_moviestreams']     = '';
$lang['warez_search']           = '';
$lang['warez_porn']             = '';
$lang['warez_usenet']           = '';
$lang['warez_scripts']          = '';
$lang['warez_torrent']          = '';
// Board Redirection Site
$lang['out_home']               = '';
$lang['out_report']             = '';
$lang['out_voteForUs']          = '';
$lang['out_vote']               = '';
$lang['out_closeFrame']         = '';
$lang['out_redirectingTo']      = '';
$lang['out_redirectingIn']      = '';
$lang['out_iframeText1']        = '';
$lang['out_iframeText2']        = '';
// FAQ site
$lang['faq_head']                 = '';
// Link
$lang['faq_menu_link']                            = '';
$lang['faq_menu_link_question_linkStatusColors']  = '';
$lang['faq_menu_link_answer_linkStatusColors']    = '';;
$lang['faq_menu_link_question_linkOffline']       = '';
$lang['faq_menu_link_answer_linkOffline']         = '';
$lang['faq_menu_link_question_addedLink']         	 = '';
$lang['faq_menu_link_answer_addedLink']           	 = '';
$lang['faq_menu_link_question_socialData']       	 = '';
$lang['faq_menu_link_answer_socialData']         	 = '';
// Privacy
$lang['faq_menu_privacy']                            = '';
$lang['faq_menu_privacy_question_terms']             = '';
$lang['faq_menu_privacy_answer_terms']               = '';
$lang['faq_menu_privacy_question_useLicense']        = '';
$lang['faq_menu_privacy_answer_useLicense']          = '';
$lang['faq_menu_privacy_question_disclaimer']        = '';
$lang['faq_menu_privacy_answer_disclaimer']          = '';
$lang['faq_menu_privacy_question_limitations']       = '';
$lang['faq_menu_privacy_answer_limitations']         = '';
$lang['faq_menu_privacy_question_accuracy']          = '';
$lang['faq_menu_privacy_answer_accuracy']            = '';
$lang['faq_menu_privacy_question_links']             = '';
$lang['faq_menu_privacy_answer_links']               = '';
$lang['faq_menu_privacy_question_modifications']     = '';
$lang['faq_menu_privacy_answer_modifications']       = '';
$lang['faq_menu_privacy_question_governingLaw']      = '';
$lang['faq_menu_privacy_answer_governingLaw']        = '';
$lang['faq_menu_privacy_question_piwik']             = '';
$lang['faq_menu_privacy_answer_piwik']               = '';
// Advertisement
$lang['faq_menu_advertisement']                      = '';
$lang['faq_menu_advertisement_question_banner']      = '';
$lang['faq_menu_advertisement_answer_banner']        = '';
?>
